services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.10
